# Generated by Django 6.0.5 on 2026-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avtar',
            field=models.ImageField(blank=True, default='person/avatar.jpeg', null=True, upload_to='profile'),
        ),
    ]
